SK cuda
MPIfR-BDG/psrdada_cpp pull request #22
Opened 2020-09-15 09:36 UTC by sakthipriyas

2020-09-23 08:35 UTC, TobiasWinchen requested changes
In addition to few comments on specific cod lines, some general things that should be addressed before merging:
- Include guards are missing
- If the thrust version is obsolete, it should be removed and the naming adopted. The same goes for the CPU version. If it is only needed for testing, it should be moved to the test folder.
- The ReadData method is not used. It should be explained why it is needed or be removed. 
- All GPU compute is currently done in the default stream. The user of the class needs to b able to set the stream stream.

In the SKReplacement class several internal parameter-less methods are used (get_clean_window_indices(),  get_rfi_window_indices, compute_clean_data_statistics) that modify the internal state of the class. This makes the code hard to follow.

2020-09-23 08:35 UTC, TobiasWinchen commented on psrdada_cpp/effelsberg/edd/SKRfiReplacement.hpp
> +    SKRfiReplacement(const std::vector<int> &rfi_status);
The RFI Status should not be passed on construction as it is specific to one data block. Pass it for very call of replac_rfi_data

2020-09-23 08:35 UTC, TobiasWinchen commented on psrdada_cpp/effelsberg/edd/SKRfiReplacementCuda.cuh
> +#define DEFAULT_NUM_CLEAN_WINDOWS 1 //number of clean windows used for computing DataStatistics
Why is this a global constant and not a parameter?

2020-09-23 08:35 UTC, TobiasWinchen commented on psrdada_cpp/effelsberg/edd/SpectralKurtosis.hpp
> +#define DEFAULT_SK_MIN 0.9
Define in constructor only - what is the value of having additional macros?

2020-09-28 09:07 UTC, sakthipriyas commented on psrdada_cpp/effelsberg/edd/src/SKRfiReplacementCuda.cu
> +    get_rfi_window_indices();
get_rfi_window_indices() and get_clean_window_indices() initializes the class members _rfi_window_indices and _clean_window_indices which are device vectors.

2020-09-29 07:33 UTC, sakthipriyas commented on psrdada_cpp/effelsberg/edd/SpectralKurtosisCuda.cuh
> +    SpectralKurtosisCuda(std::size_t nchannels, std::size_t window_size, float sk_min = DEFAULT_SK_MIN,
This is not clear to me. Do you mean that the input stream should be passed to the constructor and has to be stored as a class member for further processing? In the implementation, the input stream is passed in compute_sk() function to avoid any device copies.

2020-09-29 07:35 UTC, sakthipriyas commented on psrdada_cpp/effelsberg/edd/SpectralKurtosisCuda.cuh
> +#define DEFAULT_SK_MIN 0.9
I could make them as class default variables. But I am still trying to figure out how to make sk_min and sk_max as optional parameters in constructor. But, is this what you meant?

2020-09-29 07:37 UTC, sakthipriyas commented on psrdada_cpp/effelsberg/edd/src/SKRfiReplacementCuda.cu
> +    _ref_sd = std::sqrt(thrust::transform_reduce(_clean_data.begin(), _clean_data.end(), mean_subtraction_square(_ref_mean),
Both real and imaginary distributions have the same mean and standard deviation. Included this comment in the code.

2020-09-29 07:42 UTC, sakthipriyas commented on psrdada_cpp/effelsberg/edd/SKRfiReplacement.hpp
> +    SKRfiReplacement(const std::vector<int> &rfi_status);
Yes. This has been fixed in coda version.

2020-09-29 07:50 UTC, sakthipriyas commented on psrdada_cpp/effelsberg/edd/SKRfiReplacementCuda.cuh
> +#define DEFAULT_NUM_CLEAN_WINDOWS 1 //number of clean windows used for computing DataStatistics
Agreed. It doesn't have to be a macro. This reminds me to implement a case when the entire channel is with RFI (100% RFI) and there are no clean windows. In this case, no RFI replacement should happen in the function call.

2020-09-29 08:43 UTC, sakthipriyas commented on psrdada_cpp/effelsberg/edd/SKRfiReplacementCuda.cuh
> +#define DEFAULT_NUM_CLEAN_WINDOWS 1 //number of clean windows used for computing DataStatistics
I had that condition (if RFI = 100%) check implemented already.

2020-09-30 09:00 UTC, TobiasWinchen commented on psrdada_cpp/effelsberg/edd/SpectralKurtosisCuda.cuh
> +#define DEFAULT_SK_MIN 0.9
You should IMO just use     ` SpectralKurtosisCuda(std::size_t nchannels, std::size_t window_size, float sk_min = 0.9, ...)  ` and not have an extra define. I don;t see any benefit,. It makes the code harder to read and bears the risk that it is used in the code somewhere where it shouldn't be used but the value of the sk_min variable should be used.

2020-09-30 09:59 UTC, TobiasWinchen commented on psrdada_cpp/effelsberg/edd/SpectralKurtosisCuda.cuh
> +    SpectralKurtosisCuda(std::size_t nchannels, std::size_t window_size, float sk_min = DEFAULT_SK_MIN,
The actual kernel calls as e.g.: `compute_sk_kernel<<<gridSize, blockSize>>>(...)`  should use a user defined stream `compute_sk_kernel<<<gridSize, blockSize, sharedmemsize, STREAM >>>(...)`

2020-10-07 07:02 UTC, TobiasWinchen requested changes
The SKRfiReplacementCuda class needs some restructuring as indicated below because the duplication of information in internal member variables is unnecessary and introduced a bug.

2020-11-16 13:53 UTC, merged